% analyze properties of bistable four-bar linkage generated by optimization

% find angle swept through by link l_AC
r_AC1 = r_C1 - r_A1;
r_AC2 = r_C2 - r_A2;
ang_AC = acos(dot(r_AC1, r_AC2)/(norm(r_AC1)*norm(r_AC2)));
ang_AC_deg = rad2deg(ang_AC);

% find angle swept through by link l_CD
r_DC1 = r_C1 - r_D1;
r_DC2 = r_C2 - r_D2;
ang_DC = acos(dot(r_DC1, r_DC2)/(norm(r_DC1)*norm(r_DC2)));
ang_DC_deg = rad2deg(ang_DC);

